#!/usr/bin/env bash
# print domains and subdomains

print_domain_sub () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_domain_sub "$2.$1" "$2"
else
    print_domain_sub "www.$1" "www"
    print_domain_sub "lb-01.$1" "lb-01"
    print_domain_sub "web-01.$1" "web-01"
    print_domain_sub "web-02.$1" "web-02"
fi
