#!/usr/bin/env bash
#  list of currently running processes.
#Requirements:
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy
ps -e -o pid,user,%cpu,%mem,vsz,rss,tty,stat,start,time,command
